spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/brian
    driver-class-name: org.postgresql.Driver
    username: briancode
    password: password

  application:
    name: spring-boot

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect